{u'description': [u"alunduil's personal overlay"],
 u'feeds': [u'https://github.com/alunduil/alunduil-overlay/commits/master.atom'],
 u'homepage': u'https://github.com/alunduil/alunduil-overlay',
 u'irc': None,
 u'name': u'alunduil',
 u'official': True,
 u'owner_email': u'alunduil@gentoo.org',
 u'owner_name': u'Alex Brandt',
 u'priority': 50,
 u'quality': u'experimental',
 u'sources': [(u'https://github.com/alunduil/alunduil-overlay.git',
               u'Git',
               u''),
              (u'git://github.com/alunduil/alunduil-overlay.git',
               u'Git',
               u''),
              (u'git@github.com:alunduil/alunduil-overlay.git', u'Git', u'')],
 u'status': u'official',
 u'supported': True}
$ pmaint sync alunduil
WARNING:pkgcore:repository at '/home/mgorny/repos/steveeJ' has unsupported profile format(s): 'profile-set'
WARNING:pkgcore:repository at '/home/mgorny/repos/steveeJ' has unsupported profile format(s): 'profile-set'
Already up-to-date.
*** syncing alunduil
*** synced alunduil
 * Sync succeeded
$ pmaint regen -t 2 alunduil
WARNING:pkgcore:repository at '/home/mgorny/repos/steveeJ' has unsupported profile format(s): 'profile-set'
WARNING:pkgcore:repository at '/home/mgorny/repos/steveeJ' has unsupported profile format(s): 'profile-set'
!!! caught exception bytes_ro_StringIO instance has no attribute '__len__' while processing ebuild src: app-portage/etest-9999
!!! caught exception bytes_ro_StringIO instance has no attribute '__len__' while processing ebuild src: dev-python/aiohttp-0.16.6
!!! !!! caught exception bytes_ro_StringIO instance has no attribute '__len__' while processing ebuild src: dev-python/debtcollector-0.6.0
!!! caught exception bytes_ro_StringIO instance has no attribute '__len__' while processing ebuild src: app-emulation/docker-compose-1.3.3
caught exception bytes_ro_StringIO instance has no attribute '__len__' while processing ebuild src: media-fonts/monoid-9999
!!! caught exception bytes_ro_StringIO instance has no attribute '__len__' while processing ebuild src: dev-python/os-client-config-1.6.1
!!! caught exception bytes_ro_StringIO instance has no attribute '__len__' while processing ebuild src: dev-python/nose2-0.5.0
caught exception bytes_ro_StringIO instance has no attribute '__len__' while processing ebuild src: dev-python/oslo-i18n-2.2.0
!!! caught exception bytes_ro_StringIO instance has no attribute '__len__' while processing ebuild src: dev-python/oslo-serialization-1.7.0caught exception bytes_ro_StringIO instance has no attribute '__len__' while processing ebuild src: dev-python/oslo-config-2.1.0

!!! caught exception bytes_ro_StringIO instance has no attribute '__len__' while processing ebuild src: dev-python/oslo-utils-2.1.0
!!! caught exception bytes_ro_StringIO instance has no attribute '__len__' while processing ebuild src: dev-python/mox3-0.8.0
!!! !!! !!! !!! !!! caught exception bytes_ro_StringIO instance has no attribute '__len__' while processing ebuild src: app-backup/holland-backup-xtrabackup-1.0.10
caught exception bytes_ro_StringIO instance has no attribute '__len__' while processing ebuild src: dev-python/oslotest-1.9.0
caught exception bytes_ro_StringIO instance has no attribute '__len__' while processing ebuild src: dev-python/python-termstyle-0.1.10
 * Cache regenerated successfully
